provider: anthropic
discovered_at: '2025-06-06T14:31:23.083862'
endpoints:
- chat
- messages
features:
- tool_use
- structured_outputs
- system_messages
- multiple_images
- computer_use
- document_understanding
- context_caching
- streaming
- json_mode
- prompt_caching
- xml_mode
- batch_processing
- usage_tracking
- rate_limiting_headers
- latex_rendering
- code_execution
- long_context
- cost_tracking
- vision
- function_calling
model_capabilities:
  claude-opus-4-20250514:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - system_messages
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-sonnet-4-20250514:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - system_messages
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-3-7-sonnet-20250219:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - vision
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-3-5-sonnet-20241022:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - document_understanding
    - vision
    - streaming
    - json_mode
    - latex_rendering
    - function_calling
    - computer_use
    - xml_mode
    - system_messages
  claude-3-5-haiku-20241022:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - document_understanding
    - vision
    - streaming
    - json_mode
    - latex_rendering
    - function_calling
    - computer_use
    - xml_mode
    - system_messages
  claude-3-5-sonnet-20240620:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - document_understanding
    - vision
    - streaming
    - json_mode
    - latex_rendering
    - function_calling
    - computer_use
    - xml_mode
    - system_messages
  claude-3-haiku-20240307:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - vision
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-3-opus-20240229:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - vision
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-3-sonnet-20240229:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - structured_outputs
    - long_context
    - system_messages
    - vision
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-2.1:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - system_messages
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
  claude-2.0:
    context_window: 200000
    max_output_tokens: 4096
    capabilities:
    - system_messages
    - streaming
    - json_mode
    - function_calling
    - xml_mode
    - system_messages
