provider: anyscale
models:
  anyscale/mistralai/Mistral-7B-Instruct-v0.1:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
    - function_calling
  anyscale/mistralai/Mixtral-8x7B-Instruct-v0.1:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
    - function_calling
  anyscale/mistralai/Mixtral-8x22B-Instruct-v0.1:
    context_window: 65536
    max_output_tokens: 65536
    pricing:
      input: 0.9
      output: 0.9
    capabilities:
    - streaming
    - function_calling
  anyscale/HuggingFaceH4/zephyr-7b-beta:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
  anyscale/google/gemma-7b-it:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
  anyscale/meta-llama/Llama-2-7b-chat-hf:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
  anyscale/meta-llama/Llama-2-13b-chat-hf:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.25
      output: 0.25
    capabilities:
    - streaming
  anyscale/meta-llama/Llama-2-70b-chat-hf:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 1.0
      output: 1.0
    capabilities:
    - streaming
  anyscale/codellama/CodeLlama-34b-Instruct-hf:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 1.0
      output: 1.0
    capabilities:
    - streaming
  anyscale/codellama/CodeLlama-70b-Instruct-hf:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 1.0
      output: 1.0
    capabilities:
    - streaming
  anyscale/meta-llama/Meta-Llama-3-8B-Instruct:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
  anyscale/meta-llama/Meta-Llama-3-70B-Instruct:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 1.0
      output: 1.0
    capabilities:
    - streaming
default_model: anyscale/mistralai/Mistral-7B-Instruct-v0.1
