provider: azure_ai
models:
  azure_ai/deepseek-r1:
    context_window: 128000
    max_output_tokens: 8192
    pricing:
      input: 1.35
      output: 5.4
    capabilities:
    - streaming
    - reasoning
    - tool_choice
  azure_ai/deepseek-v3:
    context_window: 128000
    max_output_tokens: 8192
    pricing:
      input: 1.14
      output: 4.56
    capabilities:
    - streaming
    - tool_choice
  azure_ai/deepseek-v3-0324:
    context_window: 128000
    max_output_tokens: 8192
    pricing:
      input: 1.14
      output: 4.56
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/jamba-instruct:
    context_window: 70000
    max_output_tokens: 4096
    pricing:
      input: 0.5
      output: 0.7
    capabilities:
    - streaming
    - tool_choice
  azure_ai/mistral-nemo:
    context_window: 131072
    max_output_tokens: 4096
    pricing:
      input: 0.15
      output: 0.15
    capabilities:
    - streaming
    - function_calling
  azure_ai/mistral-medium-2505:
    context_window: 131072
    max_output_tokens: 8191
    pricing:
      input: 0.4
      output: 2.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/mistral-large:
    context_window: 32000
    max_output_tokens: 8191
    pricing:
      input: 4.0
      output: 12.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/mistral-small:
    context_window: 32000
    max_output_tokens: 8191
    pricing:
      input: 1.0
      output: 3.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/mistral-small-2503:
    context_window: 128000
    max_output_tokens: 128000
    pricing:
      input: 1.0
      output: 3.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  azure_ai/mistral-large-2407:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 2.0
      output: 6.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/mistral-large-latest:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 2.0
      output: 6.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/ministral-3b:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.04
      output: 0.04
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/Llama-3.2-11B-Vision-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 0.37
      output: 0.37
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  azure_ai/Llama-3.3-70B-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 0.71
      output: 0.71
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/Llama-4-Scout-17B-16E-Instruct:
    context_window: 10000000
    max_output_tokens: 16384
    pricing:
      input: 0.2
      output: 0.78
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  azure_ai/Llama-4-Maverick-17B-128E-Instruct-FP8:
    context_window: 1000000
    max_output_tokens: 16384
    pricing:
      input: 1.41
      output: 0.35
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  azure_ai/Llama-3.2-90B-Vision-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 2.04
      output: 2.04
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  azure_ai/Meta-Llama-3-70B-Instruct:
    context_window: 8192
    max_output_tokens: 2048
    pricing:
      input: 1.1
      output: 0.37
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Meta-Llama-3.1-8B-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 0.3
      output: 0.61
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Meta-Llama-3.1-70B-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 2.68
      output: 3.54
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Meta-Llama-3.1-405B-Instruct:
    context_window: 128000
    max_output_tokens: 2048
    pricing:
      input: 5.33
      output: 16.0
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-4-mini-instruct:
    context_window: 131072
    max_output_tokens: 4096
    pricing:
      input: 0.075
      output: 0.3
    capabilities:
    - streaming
    - function_calling
  azure_ai/Phi-4-multimodal-instruct:
    context_window: 131072
    max_output_tokens: 4096
    pricing:
      input: 0.08
      output: 0.32
    capabilities:
    - streaming
    - function_calling
    - vision
    - audio_input
  azure_ai/Phi-4:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.125
      output: 0.5
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  azure_ai/Phi-3.5-mini-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.13
      output: 0.52
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3.5-vision-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.13
      output: 0.52
    capabilities:
    - streaming
    - vision
    - tool_choice
  azure_ai/Phi-3.5-MoE-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.16
      output: 0.64
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-mini-4k-instruct:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.13
      output: 0.52
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-mini-128k-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.13
      output: 0.52
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-small-8k-instruct:
    context_window: 8192
    max_output_tokens: 4096
    pricing:
      input: 0.15
      output: 0.6
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-small-128k-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.15
      output: 0.6
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-medium-4k-instruct:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.17
      output: 0.68
    capabilities:
    - streaming
    - tool_choice
  azure_ai/Phi-3-medium-128k-instruct:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 0.17
      output: 0.68
    capabilities:
    - streaming
    - tool_choice
  azure_ai/cohere-rerank-v3-multilingual:
    context_window: 4096
    max_output_tokens: 4096
    mode: rerank
  azure_ai/cohere-rerank-v3-english:
    context_window: 4096
    max_output_tokens: 4096
    mode: rerank
  azure_ai/Cohere-embed-v3-english:
    context_window: 512
    pricing:
      input: 0.1
      output: 0.0
    mode: embedding
  azure_ai/Cohere-embed-v3-multilingual:
    context_window: 512
    pricing:
      input: 0.1
      output: 0.0
    mode: embedding
  azure_ai/embed-v-4-0:
    context_window: 128000
    pricing:
      input: 0.12
      output: 0.0
    mode: embedding
    supported_endpoints:
    - /v1/embeddings
    supported_modalities:
    - text
    - image
default_model: azure_ai/deepseek-r1
