# AWS Bedrock models configuration
# Pricing per 1M tokens (as of May 2025) - non-batch pricing

provider: bedrock
default_model: "claude-3-5-sonnet"

models:
  # Anthropic models
  claude-opus-4:
    context_window: 200000
    pricing:
      input: 15.00
      output: 75.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-opus-4-20250514:
    context_window: 200000
    pricing:
      input: 15.00
      output: 75.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-sonnet-4:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-sonnet-4-20250514:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-7-sonnet:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-7-sonnet-20250219:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-5-sonnet:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-5-sonnet-20241022:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-5-haiku:
    context_window: 200000
    pricing:
      input: 0.80
      output: 4.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-5-haiku-20241022:
    context_window: 200000
    pricing:
      input: 0.80
      output: 4.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-opus:
    context_window: 200000
    pricing:
      input: 15.00
      output: 75.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-opus-20240229:
    context_window: 200000
    pricing:
      input: 15.00
      output: 75.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-sonnet:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-sonnet-20240229:
    context_window: 200000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-haiku:
    context_window: 200000
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-3-haiku-20240307:
    context_window: 200000
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  claude-instant-v1:
    context_window: 100000
    pricing:
      input: 0.80
      output: 2.40
    capabilities:
      - text
      - streaming
    
  claude-v2:
    context_window: 200000
    pricing:
      input: 8.00
      output: 24.00
    capabilities:
      - text
      - streaming
    
  claude-v2.1:
    context_window: 200000
    pricing:
      input: 8.00
      output: 24.00
    capabilities:
      - text
      - streaming

  # Amazon Nova models
  nova-micro:
    context_window: 128000
    pricing:
      input: 0.035
      output: 0.14
    capabilities:
      - text
      - streaming
    
  nova-lite:
    context_window: 300000
    pricing:
      input: 0.06
      output: 0.24
    capabilities:
      - text
      - vision
      - streaming
    
  nova-pro:
    context_window: 300000
    pricing:
      input: 0.80
      output: 3.20
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  nova-premier:
    context_window: 300000
    pricing:
      input: 2.50
      output: 12.50
    capabilities:
      - text
      - vision
      - function_calling
      - streaming

  # Amazon Titan models
  titan-lite:
    context_window: 4096
    pricing:
      input: 0.30
      output: 0.40
    capabilities:
      - text
      - streaming
    
  titan-express:
    context_window: 8192
    pricing:
      input: 1.30
      output: 1.70
    capabilities:
      - text
      - streaming

  # AI21 Labs models
  jamba-1.5-large:
    context_window: 256000
    pricing:
      input: 2.00
      output: 8.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  jamba-1.5-mini:
    context_window: 256000
    pricing:
      input: 0.20
      output: 0.40
    capabilities:
      - text
      - function_calling
      - streaming
    
  jamba-instruct:
    context_window: 256000
    pricing:
      input: 0.50
      output: 0.70
    capabilities:
      - text
      - function_calling
      - streaming
    
  jurassic-2-mid:
    context_window: 8192
    pricing:
      input: 12.50
      output: 12.50
    capabilities:
      - text
      - streaming
    
  jurassic-2-ultra:
    context_window: 8192
    pricing:
      input: 18.80
      output: 18.80
    capabilities:
      - text
      - streaming

  # Cohere models
  command:
    context_window: 4096
    pricing:
      input: 1.50
      output: 2.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  command-light:
    context_window: 4096
    pricing:
      input: 0.30
      output: 0.60
    capabilities:
      - text
      - function_calling
      - streaming
    
  command-r-plus:
    context_window: 128000
    pricing:
      input: 3.00
      output: 15.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  command-r:
    context_window: 128000
    pricing:
      input: 0.50
      output: 1.50
    capabilities:
      - text
      - function_calling
      - streaming

  # DeepSeek models
  deepseek-r1:
    context_window: 128000
    pricing:
      input: 1.35
      output: 5.40
    capabilities:
      - text
      - reasoning
      - function_calling
      - streaming