provider: cerebras
models:
  cerebras/llama3.1-8b:
    context_window: 128000
    max_output_tokens: 128000
    pricing:
      input: 0.1
      output: 0.1
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  cerebras/llama3.1-70b:
    context_window: 128000
    max_output_tokens: 128000
    pricing:
      input: 0.6
      output: 0.6
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  cerebras/llama-3.3-70b:
    context_window: 128000
    max_output_tokens: 128000
    pricing:
      input: 0.85
      output: 1.2
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  cerebras/qwen-3-32b:
    context_window: 128000
    max_output_tokens: 128000
    pricing:
      input: 0.4
      output: 0.8
    capabilities:
    - streaming
    - function_calling
    - tool_choice
default_model: cerebras/llama3.1-8b
