provider: cloudflare
models:
  cloudflare/@cf/meta/llama-2-7b-chat-fp16:
    context_window: 3072
    max_output_tokens: 3072
    pricing:
      input: 1.923
      output: 1.923
    capabilities:
    - streaming
  cloudflare/@cf/meta/llama-2-7b-chat-int8:
    context_window: 2048
    max_output_tokens: 2048
    pricing:
      input: 1.923
      output: 1.923
    capabilities:
    - streaming
  cloudflare/@cf/mistral/mistral-7b-instruct-v0.1:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 1.923
      output: 1.923
    capabilities:
    - streaming
  cloudflare/@hf/thebloke/codellama-7b-instruct-awq:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 1.923
      output: 1.923
    capabilities:
    - streaming
default_model: cloudflare/@cf/meta/llama-2-7b-chat-fp16
