provider: deepgram
models:
  deepgram/nova-3:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-3-general:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-3-medical:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-general:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-meeting:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-phonecall:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-voicemail:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-finance:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-conversationalai:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-video:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-drivethru:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-automotive:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-2-atc:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-general:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/nova-phonecall:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/enhanced:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/enhanced-general:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/enhanced-meeting:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/enhanced-phonecall:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/enhanced-finance:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-general:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-meeting:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-phonecall:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-voicemail:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-finance:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-conversationalai:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/base-video:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper-tiny:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper-base:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper-small:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper-medium:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
  deepgram/whisper-large:
    mode: audio_transcription
    supported_endpoints:
    - /v1/audio/transcriptions
default_model: deepgram/nova-3
