provider: openrouter
models:
  openrouter/deepseek/deepseek-r1-0528:
    context_window: 65336
    max_output_tokens: 8192
    pricing:
      input: 0.5
      output: 2.15
    capabilities:
    - streaming
    - function_calling
    - prompt_caching
    - reasoning
    - tool_choice
  openrouter/deepseek/deepseek-r1:
    context_window: 65336
    max_output_tokens: 8192
    pricing:
      input: 0.55
      output: 2.19
    capabilities:
    - streaming
    - function_calling
    - prompt_caching
    - reasoning
    - tool_choice
  openrouter/deepseek/deepseek-chat:
    context_window: 65536
    max_output_tokens: 8192
    pricing:
      input: 0.14
      output: 0.28
    capabilities:
    - streaming
    - prompt_caching
    - tool_choice
  openrouter/deepseek/deepseek-coder:
    context_window: 66000
    max_output_tokens: 4096
    pricing:
      input: 0.14
      output: 0.28
    capabilities:
    - streaming
    - prompt_caching
    - tool_choice
  openrouter/microsoft/wizardlm-2-8x22b:nitro:
    context_window: 65536
    pricing:
      input: 1.0
      output: 1.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/google/gemini-2.5-pro:
    context_window: 1048576
    max_output_tokens: 8192
    pricing:
      input: 1.25
      output: 10.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - audio_output
    - structured_output
    - system_messages
    - tool_choice
  openrouter/google/gemini-pro-1.5:
    context_window: 1000000
    max_output_tokens: 8192
    pricing:
      input: 2.5
      output: 7.5
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/google/gemini-2.0-flash-001:
    context_window: 1048576
    max_output_tokens: 8192
    pricing:
      input: 0.1
      output: 0.4
    capabilities:
    - streaming
    - function_calling
    - vision
    - audio_output
    - structured_output
    - system_messages
    - tool_choice
  openrouter/google/gemini-2.5-flash:
    context_window: 1048576
    max_output_tokens: 8192
    pricing:
      input: 0.3
      output: 2.5
    capabilities:
    - streaming
    - function_calling
    - vision
    - audio_output
    - structured_output
    - system_messages
    - tool_choice
  openrouter/mistralai/mixtral-8x22b-instruct:
    context_window: 65536
    pricing:
      input: 0.65
      output: 0.65
    capabilities:
    - streaming
    - tool_choice
  openrouter/cohere/command-r-plus:
    context_window: 128000
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/databricks/dbrx-instruct:
    context_window: 32768
    pricing:
      input: 0.6
      output: 0.6
    capabilities:
    - streaming
    - tool_choice
  openrouter/anthropic/claude-3-haiku:
    context_window: 200000
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/anthropic/claude-3-5-haiku:
    context_window: 200000
    pricing:
      input: 1.0
      output: 5.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  openrouter/anthropic/claude-3-haiku-20240307:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/anthropic/claude-3-5-haiku-20241022:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 1.0
      output: 5.0
    capabilities:
    - streaming
    - function_calling
    - tool_choice
  openrouter/anthropic/claude-3.5-sonnet:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/anthropic/claude-3.5-sonnet:beta:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/anthropic/claude-3.7-sonnet:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - reasoning
    - tool_choice
  openrouter/anthropic/claude-3.7-sonnet:beta:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - reasoning
    - tool_choice
  openrouter/anthropic/claude-3-sonnet:
    context_window: 200000
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/anthropic/claude-sonnet-4:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - reasoning
    - tool_choice
  openrouter/mistralai/mistral-large:
    context_window: 32000
    pricing:
      input: 8.0
      output: 24.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/mistralai/mistral-small-3.1-24b-instruct:
    context_window: 32000
    pricing:
      input: 0.1
      output: 0.3
    capabilities:
    - streaming
    - tool_choice
  openrouter/mistralai/mistral-small-3.2-24b-instruct:
    context_window: 32000
    pricing:
      input: 0.1
      output: 0.3
    capabilities:
    - streaming
    - tool_choice
  openrouter/cognitivecomputations/dolphin-mixtral-8x7b:
    context_window: 32769
    pricing:
      input: 0.5
      output: 0.5
    capabilities:
    - streaming
    - tool_choice
  openrouter/google/gemini-pro-vision:
    context_window: 45875
    pricing:
      input: 0.125
      output: 0.375
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/fireworks/firellava-13b:
    context_window: 4096
    pricing:
      input: 0.2
      output: 0.2
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-3-8b-instruct:free:
    context_window: 8192
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-3-8b-instruct:extended:
    context_window: 16384
    pricing:
      input: 0.225
      output: 2.25
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-3-70b-instruct:nitro:
    context_window: 8192
    pricing:
      input: 0.9
      output: 0.9
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-3-70b-instruct:
    context_window: 8192
    pricing:
      input: 0.59
      output: 0.79
    capabilities:
    - streaming
    - tool_choice
  openrouter/openai/o1:
    context_window: 200000
    max_output_tokens: 100000
    pricing:
      input: 15.0
      output: 60.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - system_messages
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o1-mini:
    context_window: 128000
    max_output_tokens: 65536
    pricing:
      input: 3.0
      output: 12.0
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o1-mini-2024-09-12:
    context_window: 128000
    max_output_tokens: 65536
    pricing:
      input: 3.0
      output: 12.0
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o1-preview:
    context_window: 128000
    max_output_tokens: 32768
    pricing:
      input: 15.0
      output: 60.0
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o1-preview-2024-09-12:
    context_window: 128000
    max_output_tokens: 32768
    pricing:
      input: 15.0
      output: 60.0
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o3-mini:
    context_window: 128000
    max_output_tokens: 65536
    pricing:
      input: 1.1
      output: 4.4
    capabilities:
    - streaming
    - function_calling
    - reasoning
    - parallel_function_calling
    - tool_choice
  openrouter/openai/o3-mini-high:
    context_window: 128000
    max_output_tokens: 65536
    pricing:
      input: 1.1
      output: 4.4
    capabilities:
    - streaming
    - function_calling
    - reasoning
    - parallel_function_calling
    - tool_choice
  openai/gpt-4.1-nano:
    context_window: 1047576
    max_output_tokens: 4096
    pricing:
      input: 0.1
      output: 0.4
    capabilities:
    - streaming
    - function_calling
    - vision
    - parallel_function_calling
    - tool_choice
  openrouter/openai/gpt-4o:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 2.5
      output: 10.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - parallel_function_calling
    - tool_choice
  openrouter/openai/gpt-4o-2024-05-13:
    context_window: 128000
    max_output_tokens: 4096
    pricing:
      input: 5.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - parallel_function_calling
    - tool_choice
  openrouter/openai/gpt-4-vision-preview:
    context_window: 130000
    pricing:
      input: 10.0
      output: 30.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/openai/gpt-3.5-turbo:
    context_window: 4095
    pricing:
      input: 1.5
      output: 2.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/openai/gpt-3.5-turbo-16k:
    context_window: 16383
    pricing:
      input: 3.0
      output: 4.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/openai/gpt-4:
    context_window: 8192
    pricing:
      input: 30.0
      output: 60.0
    capabilities:
    - streaming
    - tool_choice
  openrouter/anthropic/claude-instant-v1:
    context_window: 100000
    max_output_tokens: 8191
    pricing:
      input: 1.63
      output: 5.51
    capabilities:
    - streaming
    - tool_choice
  openrouter/anthropic/claude-2:
    context_window: 100000
    max_output_tokens: 8191
    pricing:
      input: 11.02
      output: 32.68
    capabilities:
    - streaming
    - tool_choice
  openrouter/anthropic/claude-3-opus:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 15.0
      output: 75.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  openrouter/google/palm-2-chat-bison:
    context_window: 25804
    pricing:
      input: 0.5
      output: 0.5
    capabilities:
    - streaming
    - tool_choice
  openrouter/google/palm-2-codechat-bison:
    context_window: 20070
    pricing:
      input: 0.5
      output: 0.5
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-2-13b-chat:
    context_window: 4096
    pricing:
      input: 0.2
      output: 0.2
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/llama-2-70b-chat:
    context_window: 4096
    pricing:
      input: 1.5
      output: 1.5
    capabilities:
    - streaming
    - tool_choice
  openrouter/meta-llama/codellama-34b-instruct:
    context_window: 8192
    pricing:
      input: 0.5
      output: 0.5
    capabilities:
    - streaming
    - tool_choice
  openrouter/nousresearch/nous-hermes-llama2-13b:
    context_window: 4096
    pricing:
      input: 0.2
      output: 0.2
    capabilities:
    - streaming
    - tool_choice
  openrouter/mancer/weaver:
    context_window: 8000
    pricing:
      input: 5.625
      output: 5.625
    capabilities:
    - streaming
    - tool_choice
  openrouter/gryphe/mythomax-l2-13b:
    context_window: 8192
    pricing:
      input: 1.875
      output: 1.875
    capabilities:
    - streaming
    - tool_choice
  openrouter/jondurbin/airoboros-l2-70b-2.1:
    context_window: 4096
    pricing:
      input: 13.875
      output: 13.875
    capabilities:
    - streaming
    - tool_choice
  openrouter/undi95/remm-slerp-l2-13b:
    context_window: 6144
    pricing:
      input: 1.875
      output: 1.875
    capabilities:
    - streaming
    - tool_choice
  openrouter/pygmalionai/mythalion-13b:
    context_window: 4096
    pricing:
      input: 1.875
      output: 1.875
    capabilities:
    - streaming
    - tool_choice
  openrouter/mistralai/mistral-7b-instruct:
    context_window: 8192
    pricing:
      input: 0.13
      output: 0.13
    capabilities:
    - streaming
    - tool_choice
  openrouter/mistralai/mistral-7b-instruct:free:
    context_window: 8192
    capabilities:
    - streaming
    - tool_choice
  openrouter/qwen/qwen-2.5-coder-32b-instruct:
    context_window: 33792
    max_output_tokens: 33792
    pricing:
      input: 0.18
      output: 0.18
    capabilities:
    - streaming
    - tool_choice
default_model: openrouter/deepseek/deepseek-r1-0528
