# OpenAI models configuration
# Pricing per 1M tokens (as of May 2025)

provider: openai
default_model: "gpt-4.1-mini"

models:
  # GPT-4.1 series
  gpt-4.1:
    context_window: 1000000
    pricing:
      input: 2.00
      output: 8.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.1-2025-04-14:
    context_window: 1000000
    pricing:
      input: 2.00
      output: 8.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.1-mini:
    context_window: 1000000
    pricing:
      input: 0.40
      output: 1.60
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.1-mini-2025-04-14:
    context_window: 1000000
    pricing:
      input: 0.40
      output: 1.60
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.1-nano:
    context_window: 1000000
    pricing:
      input: 0.10
      output: 0.40
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.1-nano-2025-04-14:
    context_window: 1000000
    pricing:
      input: 0.10
      output: 0.40
    capabilities:
      - text
      - function_calling
      - streaming

  # GPT-4.5 preview
  gpt-4.5-preview:
    context_window: 128000
    pricing:
      input: 75.00
      output: 150.00
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-4.5-preview-2025-02-27:
    context_window: 128000
    pricing:
      input: 75.00
      output: 150.00
    capabilities:
      - text
      - function_calling
      - streaming

  # GPT-4o series
  gpt-4o:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  gpt-4o-2024-08-06:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  gpt-4o-audio-preview:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - audio
      - function_calling
      - streaming
    
  gpt-4o-audio-preview-2024-12-17:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - audio
      - function_calling
      - streaming
    
  gpt-4o-realtime-preview:
    context_window: 128000
    pricing:
      input: 5.00
      output: 20.00
    capabilities:
      - text
      - audio
      - realtime
      - function_calling
    
  gpt-4o-realtime-preview-2024-12-17:
    context_window: 128000
    pricing:
      input: 5.00
      output: 20.00
    capabilities:
      - text
      - audio
      - realtime
      - function_calling
    
  gpt-4o-mini:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  gpt-4o-mini-2024-07-18:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - vision
      - function_calling
      - streaming
    
  gpt-4o-mini-audio-preview:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - audio
      - function_calling
      - streaming
    
  gpt-4o-mini-audio-preview-2024-12-17:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - audio
      - function_calling
      - streaming
    
  gpt-4o-mini-realtime-preview:
    context_window: 128000
    pricing:
      input: 0.60
      output: 2.40
    capabilities:
      - text
      - audio
      - realtime
      - function_calling
    
  gpt-4o-mini-realtime-preview-2024-12-17:
    context_window: 128000
    pricing:
      input: 0.60
      output: 2.40
    capabilities:
      - text
      - audio
      - realtime
      - function_calling

  # O-series reasoning models
  o1:
    context_window: 200000
    pricing:
      input: 15.00
      output: 60.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o1-2024-12-17:
    context_window: 200000
    pricing:
      input: 15.00
      output: 60.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o1-pro:
    context_window: 200000
    pricing:
      input: 150.00
      output: 600.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o1-pro-2025-03-19:
    context_window: 200000
    pricing:
      input: 150.00
      output: 600.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o3:
    context_window: 200000
    pricing:
      input: 10.00
      output: 40.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o3-2025-04-16:
    context_window: 200000
    pricing:
      input: 10.00
      output: 40.00
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o4-mini:
    context_window: 128000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o4-mini-2025-04-16:
    context_window: 128000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o3-mini:
    context_window: 200000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o3-mini-2025-01-31:
    context_window: 200000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o1-mini:
    context_window: 200000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling
    
  o1-mini-2024-09-12:
    context_window: 200000
    pricing:
      input: 1.10
      output: 4.40
    capabilities:
      - text
      - reasoning
      - function_calling

  # Other models
  codex-mini-latest:
    context_window: 128000
    pricing:
      input: 1.50
      output: 6.00
    capabilities:
      - text
      - code
      - function_calling
      - streaming
    
  gpt-4o-mini-search-preview:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - search
      - function_calling
      - streaming
    
  gpt-4o-mini-search-preview-2025-03-11:
    context_window: 128000
    pricing:
      input: 0.15
      output: 0.60
    capabilities:
      - text
      - search
      - function_calling
      - streaming
    
  gpt-4o-search-preview:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - search
      - function_calling
      - streaming
    
  gpt-4o-search-preview-2025-03-11:
    context_window: 128000
    pricing:
      input: 2.50
      output: 10.00
    capabilities:
      - text
      - search
      - function_calling
      - streaming
    
  computer-use-preview:
    context_window: 128000
    pricing:
      input: 3.00
      output: 12.00
    capabilities:
      - text
      - computer_use
      - function_calling
      - streaming
    
  computer-use-preview-2025-03-11:
    context_window: 128000
    pricing:
      input: 3.00
      output: 12.00
    capabilities:
      - text
      - computer_use
      - function_calling
      - streaming

  # Embedding models (output is 0 for embeddings)
  text-embedding-3-small:
    context_window: 8191
    pricing:
      input: 0.02
      output: 0.00
    capabilities:
      - embeddings
    
  text-embedding-3-large:
    context_window: 8191
    pricing:
      input: 0.13
      output: 0.00
    capabilities:
      - embeddings
    
  text-embedding-ada-002:
    context_window: 8191
    pricing:
      input: 0.10
      output: 0.00
    capabilities:
      - embeddings

  # Legacy models
  gpt-3.5-turbo:
    context_window: 16385
    pricing:
      input: 0.50
      output: 1.50
    capabilities:
      - text
      - function_calling
      - streaming
    
  gpt-3.5-turbo-16k:
    context_window: 16385
    pricing:
      input: 0.50
      output: 1.50
    capabilities:
      - text
      - function_calling
      - streaming