provider: palm
models:
  palm/chat-bison:
    context_window: 8192
    max_output_tokens: 4096
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
  palm/chat-bison-001:
    context_window: 8192
    max_output_tokens: 4096
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
  palm/text-bison:
    context_window: 8192
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    mode: completion
  palm/text-bison-001:
    context_window: 8192
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    mode: completion
  palm/text-bison-safety-off:
    context_window: 8192
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    mode: completion
  palm/text-bison-safety-recitation-off:
    context_window: 8192
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    mode: completion
default_model: palm/chat-bison
