provider: sambanova
models:
  sambanova/Meta-Llama-3.1-8B-Instruct:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.1
      output: 0.2
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - tool_choice
  sambanova/Meta-Llama-3.1-405B-Instruct:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 5.0
      output: 10.0
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - tool_choice
  sambanova/Meta-Llama-3.2-1B-Instruct:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.04
      output: 0.08
    capabilities:
    - streaming
  sambanova/Meta-Llama-3.2-3B-Instruct:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.08
      output: 0.16
    capabilities:
    - streaming
  sambanova/Llama-4-Maverick-17B-128E-Instruct:
    context_window: 131072
    max_output_tokens: 131072
    pricing:
      input: 0.63
      output: 1.8
    capabilities:
    - streaming
    - function_calling
    - vision
    - structured_output
    - tool_choice
  sambanova/Llama-4-Scout-17B-16E-Instruct:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 0.4
      output: 0.7
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - tool_choice
  sambanova/Meta-Llama-3.3-70B-Instruct:
    context_window: 131072
    max_output_tokens: 131072
    pricing:
      input: 0.6
      output: 1.2
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - tool_choice
  sambanova/Meta-Llama-Guard-3-8B:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.3
      output: 0.3
    capabilities:
    - streaming
  sambanova/Qwen3-32B:
    context_window: 8192
    max_output_tokens: 8192
    pricing:
      input: 0.4
      output: 0.8
    capabilities:
    - streaming
    - function_calling
    - reasoning
    - tool_choice
  sambanova/QwQ-32B:
    context_window: 16384
    max_output_tokens: 16384
    pricing:
      input: 0.5
      output: 1.0
    capabilities:
    - streaming
  sambanova/Qwen2-Audio-7B-Instruct:
    context_window: 4096
    max_output_tokens: 4096
    pricing:
      input: 0.5
      output: 100.0
    capabilities:
    - streaming
    - audio_input
  sambanova/DeepSeek-R1-Distill-Llama-70B:
    context_window: 131072
    max_output_tokens: 131072
    pricing:
      input: 0.7
      output: 1.4
    capabilities:
    - streaming
  sambanova/DeepSeek-R1:
    context_window: 32768
    max_output_tokens: 32768
    pricing:
      input: 5.0
      output: 7.0
    capabilities:
    - streaming
  sambanova/DeepSeek-V3-0324:
    context_window: 32768
    max_output_tokens: 32768
    pricing:
      input: 3.0
      output: 4.5
    capabilities:
    - streaming
    - function_calling
    - reasoning
    - tool_choice
default_model: sambanova/Meta-Llama-3.1-8B-Instruct
