provider: together_ai
models:
  together-ai-up-to-4b:
    pricing:
      input: 0.1
      output: 0.1
    capabilities:
    - streaming
  together-ai-4.1b-8b:
    pricing:
      input: 0.2
      output: 0.2
    capabilities:
    - streaming
  together-ai-8.1b-21b:
    context_window: 1000
    pricing:
      input: 0.3
      output: 0.3
    capabilities:
    - streaming
  together-ai-21.1b-41b:
    pricing:
      input: 0.8
      output: 0.8
    capabilities:
    - streaming
  together-ai-41.1b-80b:
    pricing:
      input: 0.9
      output: 0.9
    capabilities:
    - streaming
  together-ai-81.1b-110b:
    pricing:
      input: 1.8
      output: 1.8
    capabilities:
    - streaming
  together-ai-embedding-up-to-150m:
    pricing:
      input: 0.008
      output: 0.0
    mode: embedding
  together-ai-embedding-151m-to-350m:
    pricing:
      input: 0.016
      output: 0.0
    mode: embedding
  together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo:
    pricing:
      input: 0.18
      output: 0.18
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo:
    pricing:
      input: 0.88
      output: 0.88
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo:
    pricing:
      input: 3.5
      output: 3.5
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo:
    pricing:
      input: 0.88
      output: 0.88
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo-Free:
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1:
    pricing:
      input: 0.6
      output: 0.6
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/mistralai/Mistral-7B-Instruct-v0.1:
    capabilities:
    - streaming
    - function_calling
    - structured_output
    - parallel_function_calling
    - tool_choice
  together_ai/togethercomputer/CodeLlama-34b-Instruct:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Llama-4-Scout-17B-16E-Instruct:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/meta-llama/Llama-3.2-3B-Instruct-Turbo:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/Qwen/Qwen2.5-72B-Instruct-Turbo:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/deepseek-ai/DeepSeek-V3:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
  together_ai/mistralai/Mistral-Small-24B-Instruct-2501:
    capabilities:
    - streaming
    - function_calling
    - parallel_function_calling
    - tool_choice
default_model: together-ai-up-to-4b
