provider: vertex_ai-anthropic_models
models:
  vertex_ai/claude-3-sonnet:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  vertex_ai/claude-3-sonnet@20240229:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  vertex_ai/claude-3-5-sonnet:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-5-sonnet@20240620:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-5-sonnet-v2:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-5-sonnet-v2@20241022:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-7-sonnet@20250219:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - reasoning
    - pdf_input
    - tool_choice
    deprecation_date: '2025-06-01'
  vertex_ai/claude-opus-4:
    context_window: 200000
    max_output_tokens: 32000
    pricing:
      input: 15.0
      output: 75.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - reasoning
    - pdf_input
    - tool_choice
  vertex_ai/claude-opus-4@20250514:
    context_window: 200000
    max_output_tokens: 32000
    pricing:
      input: 15.0
      output: 75.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - reasoning
    - pdf_input
    - tool_choice
  vertex_ai/claude-sonnet-4:
    context_window: 200000
    max_output_tokens: 64000
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - reasoning
    - pdf_input
    - tool_choice
  vertex_ai/claude-sonnet-4@20250514:
    context_window: 200000
    max_output_tokens: 64000
    pricing:
      input: 3.0
      output: 15.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - prompt_caching
    - structured_output
    - reasoning
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-haiku:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  vertex_ai/claude-3-haiku@20240307:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 0.25
      output: 1.25
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  vertex_ai/claude-3-5-haiku:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 1.0
      output: 5.0
    capabilities:
    - streaming
    - function_calling
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-5-haiku@20241022:
    context_window: 200000
    max_output_tokens: 8192
    pricing:
      input: 1.0
      output: 5.0
    capabilities:
    - streaming
    - function_calling
    - pdf_input
    - tool_choice
  vertex_ai/claude-3-opus:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 15.0
      output: 75.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
  vertex_ai/claude-3-opus@20240229:
    context_window: 200000
    max_output_tokens: 4096
    pricing:
      input: 15.0
      output: 75.0
    capabilities:
    - streaming
    - function_calling
    - vision
    - tool_choice
default_model: vertex_ai/claude-3-sonnet
