provider: vertex_ai-code-chat-models
models:
  codechat-bison@latest:
    context_window: 6144
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
  codechat-bison:
    context_window: 6144
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
  codechat-bison@001:
    context_window: 6144
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
  codechat-bison@002:
    context_window: 6144
    max_output_tokens: 1024
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
  codechat-bison-32k:
    context_window: 32000
    max_output_tokens: 8192
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
  codechat-bison-32k@002:
    context_window: 32000
    max_output_tokens: 8192
    pricing:
      input: 0.125
      output: 0.125
    capabilities:
    - streaming
    - tool_choice
default_model: codechat-bison@latest
