provider: vertex_ai-image-models
models:
  vertex_ai/imagegeneration@006:
    mode: image_generation
  vertex_ai/imagen-4.0-generate-preview-06-06:
    mode: image_generation
  vertex_ai/imagen-4.0-ultra-generate-preview-06-06:
    mode: image_generation
  vertex_ai/imagen-4.0-fast-generate-preview-06-06:
    mode: image_generation
  vertex_ai/imagen-3.0-generate-002:
    mode: image_generation
  vertex_ai/imagen-3.0-generate-001:
    mode: image_generation
  vertex_ai/imagen-3.0-fast-generate-001:
    mode: image_generation
default_model: vertex_ai/imagegeneration@006
